pipeline {
  /* This way we run the same Jenkinsfile on different platforms. */
  agent { label params.AGENT_LABEL }

  parameters {
    string(
      name: 'AGENT_LABEL',
      description: 'Label for targetted CI slave host: linux/macos',
      defaultValue: params.AGENT_LABEL ?: getAgentLabel(),
    )
  }

  options {
    timestamps()
    ansiColor('xterm')
    /* This also includes wait time in the queue. */
    timeout(time: 30, unit: 'HOURS')
    /* Limit builds retained. */
    buildDiscarder(logRotator(
      numToKeepStr: '5',
      daysToKeepStr: '30',
      artifactNumToKeepStr: '3',
    ))
    /* Throttle number of concurrent builds. */
    throttleJobProperty(
      throttleEnabled: true,
      throttleOption: 'category',
      categories: ['nimbus-eth2'],
      maxConcurrentPerNode: 1,
      maxConcurrentTotal: 6
    )
    /* Abort old builds for non-main branches. */
    disableConcurrentBuilds(
      abortPrevious: !isMainBranch()
    )
  }

  environment {
    NPROC = Runtime.getRuntime().availableProcessors()
    MAKEFLAGS = "-j${env.NPROC}"
  }

  stages {
    stage('Deps') {
      steps { timeout(20) {
        /* To allow the following parallel stages. */
        sh 'make QUICK_AND_DIRTY_COMPILER=1 update'
        /* Allow the following parallel stages. */
        sh 'make deps'
        /* Download test vectors. */
        sh './scripts/setup_scenarios.sh'
      } }
    }

    stage('Finalizations 1') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '1')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '1')
          } } }
        }
      }
    }

    stage('Finalizations 2') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '2')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '2')
          } } }
        }
      }
    }

    stage('Finalizations 3') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '3')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '3')
          } } }
        }
      }
    }

    stage('Finalizations 4') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '4')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '4')
          } } }
        }
      }
    }

    stage('Finalizations 5') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '5')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '5')
          } } }
        }
      }
    }

    stage('Finalizations 6') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '6')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '6')
          } } }
        }
      }
    }

    stage('Finalizations 7') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '7')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '7')
          } } }
        }
      }
    }

    stage('Finalizations 8') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '8')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '8')
          } } }
        }
      }
    }

    stage('Finalizations 9') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '9')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '9')
          } } }
        }
      }
    }

    stage('Finalizations 10') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '10')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '10')
          } } }
        }
      }
    }

    stage('Finalizations 11') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '11')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '11')
          } } }
        }
      }
    }

    stage('Finalizations 12') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '12')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '12')
          } } }
        }
      }
    }

    stage('Finalizations 13') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '13')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '13')
          } } }
        }
      }
    }

    stage('Finalizations 14') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '14')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '14')
          } } }
        }
      }
    }

    stage('Finalizations 15') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '15')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '15')
          } } }
        }
      }
    }

    stage('Finalizations 16') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '16')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '16')
          } } }
        }
      }
    }

    stage('Finalizations 17') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '17')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '17')
          } } }
        }
      }
    }

    stage('Finalizations 18') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '18')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '18')
          } } }
        }
      }
    }

    stage('Finalizations 19') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '19')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '19')
          } } }
        }
      }
    }

    stage('Finalizations 20') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '20')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '20')
          } } }
        }
      }
    }

    stage('Finalizations 21') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '21')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '21')
          } } }
        }
      }
    }

    stage('Finalizations 22') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '22')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '22')
          } } }
        }
      }
    }

    stage('Finalizations 23') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '23')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '23')
          } } }
        }
      }
    }

    stage('Finalizations 24') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '24')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '24')
          } } }
        }
      }
    }

    stage('Finalizations 25') {
      stages {  /* parallel builds of minimal / mainnet not yet supported */
        stage('minimal') {
          steps { script { timeout(26) {
            launchLocalTestnet('minimal', '25')
          } } }
        }

        stage('mainnet') {
          steps { script { timeout(62) {
            launchLocalTestnet('mainnet', '25')
          } } }
        }
      }
    }
  }

  post {
    always {
      catchError { timeout(5) {
        archiveArtifacts(artifacts: '*.tar.gz', allowEmptyArchive: true)
      } }
      cleanWs(
        disableDeferredWipeout: true,
        deleteDirs: true
      )
    }
  }
}

def launchLocalTestnet(String name, String n) {
  /* We want to mark job as failed, but save the results. */
  try {
    sh "make local-testnet-${name}"
  } finally {
    sh "tar cjf local-testnet-${name}-${n}.tar.gz local-testnet-${name}/*.txt"
  }
}

def isMainBranch() {
  return ['stable', 'testing', 'unstable'].contains(env.BRANCH_NAME)
}

/* This allows us to use one Jenkinsfile and run
 * jobs on different platforms based on job name. */
def getAgentLabel() {
    if (params.AGENT_LABEL) { return params.AGENT_LABEL }
    /* We extract the name of the job from currentThread because
     * before an agent is picket env is not available. */
    def tokens = Thread.currentThread().getName().split('/')
    def labels = []
    /* Check if the job path contains any of the valid labels. */
    ['linux', 'macos', 'x86_64', 'aarch64', 'arm64'].each {
        if (tokens.contains(it)) { labels.add(it) }
    }
    return labels.join(' && ')
}
